2019-04-10T12:02:05.9580483+03:00;VSTestExecutionThread;Info;SpecFlow+Runner execution started
2019-04-10T12:02:05.9580483+03:00;VSTestExecutionThread;Info;SpecFlow+Runner 3.0.255 in Framework clr40 in x86 mode execution started
2019-04-10T12:02:05.9580483+03:00;VSTestExecutionThread;Info;TestAdapter Location: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\TechTalk.SpecRun.VisualStudio.TestAdapter.dll
2019-04-10T12:02:06.0999665+03:00;VSTestExecutionThread;Info;SpecRun: running tests in C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T12:02:06.0999665+03:00;VSTestExecutionThread;Info;Output folder configured to "C:\Users\niga3\source\repos\End-To-End-Testing\TestResults" (default)
2019-04-10T12:02:06.0999665+03:00;VSTestExecutionThread;Info;Profile: Tests
2019-04-10T12:02:06.1229581+03:00;VSTestExecutionThread;Info;Log file path: C:\Users\niga3\source\repos\End-To-End-Testing\TestResults\Tests_Tests_2019-04-10T120206.log
2019-04-10T12:02:06.1319481+03:00;VSTestExecutionThread;Info;SpecFlow+Runner Evaluation Mode: Please purchase at http://www.specflow.org/plus to remove test execution delay.
2019-04-10T12:02:06.1379444+03:00;Thread#13;Info;Checking license
2019-04-10T12:02:06.1529383+03:00;Thread#13;Info;Evaluation mode: test execution starts in 14 seconds... (this delay is removed in the registered version)
2019-04-10T12:02:20.1538613+03:00;Thread#13;Info;Evaluation delay finished.
2019-04-10T12:02:20.1778496+03:00;Thread#13;Info;License check completed
2019-04-10T12:02:20.1788475+03:00;Thread#13;Info;starting test run
2019-04-10T12:02:20.2008056+03:00;Thread#13;Info;Discovering target: Default
2019-04-10T12:02:20.2008056+03:00;Thread#13;Info;Discovering tests from assembly: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T12:02:20.6205648+03:00:Appdomain Disposed
2019-04-10T12:02:20.6215634+03:00;Thread#13;Info;Discovered tests from assembly: C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\Tests.dll
2019-04-10T12:02:20.6225624+03:00:Test Suite Dump
2019-04-10T12:02:20.6245618+03:00:#0: Tests/Tests - 
2019-04-10T12:02:20.6245618+03:00:#1: Default - 
2019-04-10T12:02:20.6245618+03:00:#2: Tests - 
2019-04-10T12:02:20.6245618+03:00:#3: LoginFlows - 
2019-04-10T12:02:20.6635425+03:00:#4: Error message received on incorrect login - TestAssembly:Tests/Feature:LoginFlows/Scenario:Error+message+received+on+incorrect+login
2019-04-10T12:02:20.6635425+03:00:#5: Clicking on the back button takes the user back to email input step - TestAssembly:Tests/Feature:LoginFlows/Scenario:Clicking+on+the+back+button+takes+the+user+back+to+email+input+step
2019-04-10T12:02:20.6645385+03:00:#6: Login form displayed at the end of the purchase flow - TestAssembly:Tests/Feature:LoginFlows/Scenario:Login+form+displayed+at+the+end+of+the+purchase+flow
2019-04-10T12:02:20.6645385+03:00:End: Test Suite Dump
2019-04-10T12:02:20.6905466+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:02:20.6925466+03:00:Thread#:Scheduler: testitem #4 from normal test queue 
2019-04-10T12:02:20.6925466+03:00:Thread#0:Scheduler: considering testitem #4 for thread 0
2019-04-10T12:02:20.6975221+03:00:Thread#0:TestItem#4:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:02:20.6975221+03:00:Thread#0:TestItem#4:runsOnOneOtherThreadSpecific:False
2019-04-10T12:02:20.6975221+03:00:Thread#0:TestItem#4:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:02:20.6975221+03:00:Thread#0:Scheduler: using testitem #4 for thread 0
2019-04-10T12:02:20.6995201+03:00:Thread#0:Scheduler: Test #4 is scheduled for thread
2019-04-10T12:02:20.7015171+03:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-04-10T12:02:20.7035175+03:00:Thread #0: creating new test thread executor for Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null (target: Default)
2019-04-10T12:02:20.7055158+03:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-04-10T12:02:20.7065155+03:00:Thread #0: Creating test assembly executor for execution model AppDomain
2019-04-10T12:02:20.7065155+03:00:using TechTalk.SpecRun.Framework.Execution.InProcess.InProcAppDomainTestAssemblyExecutorHost to execute tests
2019-04-10T12:02:20.7724760+03:00:Thread#0: Test #4/0 is started on thread #0
2019-04-10T12:02:20.9257516+03:00:Thread#0:T:-> Loading plugin C:\Users\niga3\source\repos\End-To-End-Testing\Tests\bin\Debug\SpecRun.Runtime.SpecFlowPlugin.dll
2019-04-10T12:02:20.9327477+03:00:Thread#0:T:-> Using default config
2019-04-10T12:02:21.0076820+03:00:Thread#0:B:Given The user accessed the login page
2019-04-10T12:02:25.1453640+03:00:Thread#0:T:done: LoginFlowsSteps.GivenTheUserAccessedTheLoginPage() (4.0s)
2019-04-10T12:02:25.1473634+03:00:Thread#0:B:When the user enters wrong credentials
2019-04-10T12:02:45.4980251+03:00:Thread#0:T:done: LoginFlowsSteps.WhenTheUserEntersWrongCredentials() (20.3s)
2019-04-10T12:02:45.4990245+03:00:Thread#0:B:Then An error message is displayed
2019-04-10T12:02:45.5459917+03:00:Thread#0:T:done: LoginFlowsSteps.ThenAnErrorMessageIsDisplayed() (0.0s)
2019-04-10T12:02:45.5559858+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:02:45.5559858+03:00:Thread#:Scheduler: testitem #5 from normal test queue 
2019-04-10T12:02:45.5559858+03:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-04-10T12:02:45.5559858+03:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:02:45.5559858+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-04-10T12:02:45.5559858+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:02:45.5559858+03:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-04-10T12:02:45.5559858+03:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-04-10T12:02:45.5559858+03:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-04-10T12:02:45.7688420+03:00:Thread#0: Test #4/0 is finished on thread #0 as Succeeded within 24.995366 seconds
2019-04-10T12:02:45.7718390+03:00:Thread#0: Test #5/0 is started on thread #0
2019-04-10T12:02:45.7728400+03:00:Thread#0:B:Given The user accessed the login page
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:02:49.8536093+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:02:49.8546069+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:49.8546069+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:49.8546069+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:02:49.8546069+03:00:Thread#0:B:When The user clicks on the back button after inputing an email
2019-04-10T12:02:49.8556073+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:49.8556073+03:00:Thread#0:B:Then The user is redirected back to email input step
2019-04-10T12:02:49.8556073+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:49.8925859+03:00:Thread#0:TestItem#5:Scheduler: reschedule tests for testitem #5
2019-04-10T12:02:49.8925859+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:02:49.8925859+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #5
2019-04-10T12:02:49.8925859+03:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-04-10T12:02:49.8925859+03:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:02:49.8925859+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-04-10T12:02:49.8925859+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:02:49.8935853+03:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-04-10T12:02:49.8935853+03:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-04-10T12:02:49.8935853+03:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-04-10T12:02:51.9014000+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:02:51.9043977+03:00:Thread#0: Test #5/0 is finished on thread #0 as Failed within 6.1325587 seconds
2019-04-10T12:02:51.9053967+03:00:Thread#0: Test #5/1 is started on thread #0
2019-04-10T12:02:51.9063926+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T12:02:51.9063926+03:00:Thread#0:B:Given The user accessed the login page
2019-04-10T12:02:53.9145146+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:02:53.9154883+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:02:53.9154883+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:02:53.9154883+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:02:53.9224836+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:02:53.9224836+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:02:53.9224836+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:02:53.9234830+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:53.9234830+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:53.9234830+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:02:53.9234830+03:00:Thread#0:B:When The user clicks on the back button after inputing an email
2019-04-10T12:02:53.9234830+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:53.9244823+03:00:Thread#0:B:Then The user is redirected back to email input step
2019-04-10T12:02:53.9244823+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:53.9254817+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:02:53.9254817+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #5
2019-04-10T12:02:53.9254817+03:00:Thread#0:Scheduler: considering testitem #5 for thread 0
2019-04-10T12:02:53.9254817+03:00:Thread#0:TestItem#5:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:02:53.9254817+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadSpecific:False
2019-04-10T12:02:53.9254817+03:00:Thread#0:TestItem#5:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:02:53.9254817+03:00:Thread#0:Scheduler: using testitem #5 for thread 0
2019-04-10T12:02:53.9254817+03:00:Thread#0:Scheduler: Test #5 is scheduled for thread
2019-04-10T12:02:53.9254817+03:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-04-10T12:02:55.9308718+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:02:55.9358966+03:00:Thread#0: Test #5/1 is finished on thread #0 as Failed within 4.0304999 seconds
2019-04-10T12:02:55.9358966+03:00:Thread#0: Test #5/2 is started on thread #0
2019-04-10T12:02:55.9368678+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T12:02:55.9378672+03:00:Thread#0:B:Given The user accessed the login page
2019-04-10T12:02:57.9461503+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:02:57.9471274+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:02:57.9471274+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:02:57.9471274+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:02:57.9471274+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:02:57.9471274+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:02:57.9481264+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:02:57.9481264+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:57.9481264+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:02:57.9481264+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:02:57.9481264+03:00:Thread#0:B:When The user clicks on the back button after inputing an email
2019-04-10T12:02:57.9491292+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:57.9491292+03:00:Thread#0:B:Then The user is redirected back to email input step
2019-04-10T12:02:57.9491292+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:02:57.9501466+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:02:57.9501466+03:00:Thread#:Scheduler: testitem #6 from normal test queue 
2019-04-10T12:02:57.9501466+03:00:Thread#0:Scheduler: considering testitem #6 for thread 0
2019-04-10T12:02:57.9501466+03:00:Thread#0:TestItem#6:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:02:57.9501466+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadSpecific:False
2019-04-10T12:02:57.9501466+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:02:57.9501466+03:00:Thread#0:Scheduler: using testitem #6 for thread 0
2019-04-10T12:02:57.9501466+03:00:Thread#0:Scheduler: Test #6 is scheduled for thread
2019-04-10T12:02:57.9501466+03:00:Thread#0:Scheduler: with testItemExecutionIndex 0
2019-04-10T12:02:59.9530974+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:02:59.9570763+03:00:Thread#0: Test #5/2 is finished on thread #0 as Failed within 4.0211797 seconds
2019-04-10T12:02:59.9580678+03:00:Thread#0: Test #6/0 is started on thread #0
2019-04-10T12:02:59.9590678+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T12:02:59.9600661+03:00:Thread#0:B:Given The user accessed a product page
2019-04-10T12:03:01.9836876+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:03:01.9846870+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:03:01.9856866+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:01.9856866+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:01.9856866+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:03:01.9856866+03:00:Thread#0:B:When The unlogged user tries to complete the purchase flow
2019-04-10T12:03:01.9856866+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:01.9856866+03:00:Thread#0:B:Then The login form is displayed
2019-04-10T12:03:01.9866860+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:01.9866860+03:00:Thread#0:TestItem#6:Scheduler: reschedule tests for testitem #6
2019-04-10T12:03:01.9866860+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:03:01.9866860+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #6
2019-04-10T12:03:01.9866860+03:00:Thread#0:Scheduler: considering testitem #6 for thread 0
2019-04-10T12:03:01.9866860+03:00:Thread#0:TestItem#6:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:03:01.9866860+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadSpecific:False
2019-04-10T12:03:01.9866860+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:03:01.9866860+03:00:Thread#0:Scheduler: using testitem #6 for thread 0
2019-04-10T12:03:01.9866860+03:00:Thread#0:Scheduler: Test #6 is scheduled for thread
2019-04-10T12:03:01.9866860+03:00:Thread#0:Scheduler: with testItemExecutionIndex 1
2019-04-10T12:03:03.9922448+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:03:03.9952592+03:00:Thread#0: Test #6/0 is finished on thread #0 as Failed within 4.0371914 seconds
2019-04-10T12:03:03.9952592+03:00:Thread#0: Test #6/1 is started on thread #0
2019-04-10T12:03:03.9962374+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T12:03:03.9962374+03:00:Thread#0:B:Given The user accessed a product page
2019-04-10T12:03:06.0073864+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:03:06.0083827+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:03:06.0083827+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:03:06.0083827+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:03:06.0083827+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:03:06.0083827+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:03:06.0093844+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:03:06.0093844+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:06.0093844+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:06.0093844+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:03:06.0093844+03:00:Thread#0:B:When The unlogged user tries to complete the purchase flow
2019-04-10T12:03:06.0093844+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:06.0103817+03:00:Thread#0:B:Then The login form is displayed
2019-04-10T12:03:06.0103817+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:06.0103817+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:03:06.0103817+03:00:Thread#:Scheduler: dequeuing a rescheduled testitem: #6
2019-04-10T12:03:06.0103817+03:00:Thread#0:Scheduler: considering testitem #6 for thread 0
2019-04-10T12:03:06.0103817+03:00:Thread#0:TestItem#6:testItemMatchesCurrentTestThread:UnSpecific
2019-04-10T12:03:06.0103817+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadSpecific:False
2019-04-10T12:03:06.0113811+03:00:Thread#0:TestItem#6:runsOnOneOtherThreadUnspecific:False
2019-04-10T12:03:06.0113811+03:00:Thread#0:Scheduler: using testitem #6 for thread 0
2019-04-10T12:03:06.0113811+03:00:Thread#0:Scheduler: Test #6 is scheduled for thread
2019-04-10T12:03:06.0113811+03:00:Thread#0:Scheduler: with testItemExecutionIndex 2
2019-04-10T12:03:08.0147024+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:03:08.0176922+03:00:Thread#0: Test #6/1 is finished on thread #0 as Failed within 4.022433 seconds
2019-04-10T12:03:08.0176922+03:00:Thread#0: Test #6/2 is started on thread #0
2019-04-10T12:03:08.0176922+03:00:Thread#0:T:warning: The previous ScenarioContext was not disposed.
2019-04-10T12:03:08.0186720+03:00:Thread#0:B:Given The user accessed a product page
2019-04-10T12:03:10.0253188+03:00:Thread#0:T:error: Unexpected error. System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:50471
2019-04-10T12:03:10.0253188+03:00:Thread#0:T:   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   --- End of inner exception stack trace ---
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at System.Net.HttpWebRequest.GetRequestStream()
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.MakeHttpRequest(HttpRequestInfo requestInfo)
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:10.0263178+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
2019-04-10T12:03:10.0273175+03:00:Thread#0:T:   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
2019-04-10T12:03:10.0273175+03:00:Thread#0:B:When The unlogged user tries to complete the purchase flow
2019-04-10T12:03:10.0273175+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:10.0273175+03:00:Thread#0:B:Then The login form is displayed
2019-04-10T12:03:10.0273175+03:00:Thread#0:T:skipped because of previous errors
2019-04-10T12:03:10.0283165+03:00:Thread#0:Scheduler: get next test for thread 0
2019-04-10T12:03:10.0283165+03:00:Thread#:Scheduler: at the end of normal test queue
2019-04-10T12:03:10.0283165+03:00:Thread#0:Scheduler: enumerator for thread is at end
2019-04-10T12:03:10.0283165+03:00:Thread#0:Scheduler: No more tests for thread
2019-04-10T12:03:12.0332221+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:03:14.0412237+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:03:16.0547817+03:00:Thread#0:T:A exception with a null response was thrown sending an HTTP request to the remote WebDriver server for URL http://localhost:50471/session//screenshot. The status of the exception was ConnectFailure, and the message was: Unable to connect to the remote server
2019-04-10T12:03:16.0567540+03:00:Thread#0: Test #6/2 is finished on thread #0 as Failed within 8.0390618 seconds
2019-04-10T12:03:16.0787443+03:00:Appdomain Disposed
2019-04-10T12:03:16.0807399+03:00:Trying to cancel thread
2019-04-10T12:03:16.0807399+03:00:Thread cancelled
2019-04-10T12:03:16.0897380+03:00:Thread#-1:Scheduler: get next test for thread -1
2019-04-10T12:03:16.0897380+03:00:Thread#:Scheduler: at the end of normal test queue
2019-04-10T12:03:16.0897380+03:00:Thread#-1:Scheduler: enumerator for thread is at end
2019-04-10T12:03:16.0967310+03:00;Thread#13;Info;test run finished
2019-04-10T12:03:16.0967310+03:00;Thread#13;Info;publishing test results
2019-04-10T12:03:16.1357083+03:00;Thread#13;Info;test results published
2019-04-10T12:03:16.1357083+03:00;Thread#13;Info;generating reports
2019-04-10T12:03:16.2996137+03:00;Thread#13;Info;Starting external report generation process
2019-04-10T12:03:18.2977915+03:00;Thread#13;Info;Successfully generated reports.
2019-04-10T12:03:18.2997899+03:00;Thread#13;Info;Successfully generated reports
2019-04-10T12:03:18.3077832+03:00:Total: 3 (test executions: 7)
2019-04-10T12:03:18.3097826+03:00:Succeeded: 1
2019-04-10T12:03:18.3107816+03:00:Ignored: 0
2019-04-10T12:03:18.3107816+03:00:Pending: 0
2019-04-10T12:03:18.3107816+03:00:Skipped: 0
2019-04-10T12:03:18.3117898+03:00:Failed: 2
2019-04-10T12:03:18.3248028+03:00;VSTestExecutionThread;Info;Adding attachments to VSTest
2019-04-10T12:03:18.3248028+03:00;VSTestExecutionThread;Info;adding Test Execution Report 'C:\Users\niga3\source\repos\End-To-End-Testing\TestResults\TestRunReport.html'
========== End of log file ==========
